import RadialTextChart from "./components/CircularTextRing";

import play from "./data/midsummer-text.json";

function getData(playObj) {
  const out = [];

  const act = playObj["1"]; // only Act 1
  if (!act) return out;

  for (const sceneKey of Object.keys(act).sort((a, b) => +a - +b)) {
    const scene = act[sceneKey];
    if (!scene) continue;

    for (const lineKey of Object.keys(scene).sort((a, b) => +a - +b)) {
      const entry = scene[lineKey];

      // spoken line objects look like: { speaker: "THESEUS.", line: "..." }
      if (entry && typeof entry === "object" && "line" in entry) {
        const character = (entry.speaker || "").trim();
        const text = (entry.line || "").trim();
        if (text) out.push({ character, line: text });
      }
      // strings (stage directions) are ignored
    }
  }

  return out;
}




export default function App() {
  
  const stuff = getData(play)

  const data = [
    " Now, fair Hippolyta, our nuptial hour ",
" Draws on apace; four happy days bring in ",
" Another moon; but oh, methinks, how slow ",
" This old moon wanes! She lingers my desires, ",
" Like to a step-dame or a dowager, ",
" Long withering out a young man’s revenue. ",
" Four days will quickly steep themselves in night; ",
" Four nights will quickly dream away the time; ",
" And then the moon, like to a silver bow ",
" New bent in heaven, shall behold the night ",
" Of our solemnities. ",
" Go, Philostrate, ",
" Stir up the Athenian youth to merriments; ",
" Awake the pert and nimble spirit of mirth; ",
" Turn melancholy forth to funerals; ",
" The pale companion is not for our pomp. ",
" Hippolyta, I woo’d thee with my sword, ",
" And won thy love doing thee injuries; ",
" But I will wed thee in another key, ",
" With pomp, with triumph, and with revelling. ",
" Happy be Theseus, our renownèd Duke! ",
" Thanks, good Egeus. What’s the news with thee? ",
" Full of vexation come I, with complaint ",
" Against my child, my daughter Hermia. ",
" Stand forth, Demetrius. My noble lord, ",
" This man hath my consent to marry her. ",
" Stand forth, Lysander. And, my gracious Duke, ",
" This man hath bewitch’d the bosom of my child. ",
" Thou, thou, Lysander, thou hast given her rhymes, ",
" And interchang’d love-tokens with my child. ",
" Thou hast by moonlight at her window sung, ",
" With feigning voice, verses of feigning love; ",
" And stol’n the impression of her fantasy ",
" With bracelets of thy hair, rings, gauds, conceits, ",
" Knacks, trifles, nosegays, sweetmeats (messengers ",
" Of strong prevailment in unharden’d youth) ",
" With cunning hast thou filch’d my daughter’s heart, ",
" Turn’d her obedience (which is due to me) ",
" To stubborn harshness. And, my gracious Duke, ",
" Be it so she will not here before your grace ",
" Consent to marry with Demetrius, ",
" I beg the ancient privilege of Athens: ",
" As she is mine I may dispose of her; ",
" Which shall be either to this gentleman ",
" Or to her death, according to our law ",
" Immediately provided in that case. ",
" What say you, Hermia? Be advis’d, fair maid. ",
" To you your father should be as a god; ",
" One that compos’d your beauties, yea, and one ",
" To whom you are but as a form in wax ",
" By him imprinted, and within his power ",
" To leave the figure, or disfigure it. ",
" Demetrius is a worthy gentleman. ",
" So is Lysander. ",
" In himself he is. ",
" But in this kind, wanting your father’s voice, ",
" The other must be held the worthier. ",
" I would my father look’d but with my eyes. ",
" Rather your eyes must with his judgment look. ",
" I do entreat your Grace to pardon me. ",
" I know not by what power I am made bold, ",
" Nor how it may concern my modesty ",
" In such a presence here to plead my thoughts: ",
" But I beseech your Grace that I may know ",
" The worst that may befall me in this case, ",
" If I refuse to wed Demetrius. ",
" Either to die the death, or to abjure ",
" For ever the society of men. ",
" Therefore, fair Hermia, question your desires, ",
" Know of your youth, examine well your blood, ",
" Whether, if you yield not to your father’s choice, ",
" You can endure the livery of a nun, ",
" For aye to be in shady cloister mew’d, ",
" To live a barren sister all your life, ",
" Chanting faint hymns to the cold fruitless moon. ",
" Thrice-blessèd they that master so their blood ",
" To undergo such maiden pilgrimage, ",
" But earthlier happy is the rose distill’d ",
" Than that which, withering on the virgin thorn, ",
" Grows, lives, and dies, in single blessedness. ",
" So will I grow, so live, so die, my lord, ",
" Ere I will yield my virgin patent up ",
" Unto his lordship, whose unwishèd yoke ",
" My soul consents not to give sovereignty. ",
" Take time to pause; and by the next new moon ",
" The sealing-day betwixt my love and me ",
" For everlasting bond of fellowship, ",
" Upon that day either prepare to die ",
" For disobedience to your father’s will, ",
" Or else to wed Demetrius, as he would, ",
" Or on Diana’s altar to protest ",
" For aye austerity and single life. ",
" Relent, sweet Hermia; and, Lysander, yield ",
" Thy crazèd title to my certain right. ",
" You have her father’s love, Demetrius. ",
" Let me have Hermia’s. Do you marry him. ",
" Scornful Lysander, true, he hath my love; ",
" And what is mine my love shall render him; ",
" And she is mine, and all my right of her ",
" I do estate unto Demetrius. ",
" I am, my lord, as well deriv’d as he, ",
" As well possess’d; my love is more than his; ",
" My fortunes every way as fairly rank’d, ",
" If not with vantage, as Demetrius’; ",
" And, which is more than all these boasts can be, ",
" I am belov’d of beauteous Hermia. ",
" Why should not I then prosecute my right? ",
" Demetrius, I’ll avouch it to his head, ",
" Made love to Nedar’s daughter, Helena, ",
" And won her soul; and she, sweet lady, dotes, ",
" Devoutly dotes, dotes in idolatry, ",
" Upon this spotted and inconstant man. ",
" I must confess that I have heard so much, ",
" And with Demetrius thought to have spoke thereof; ",
" But, being over-full of self-affairs, ",
" My mind did lose it.—But, Demetrius, come, ",
" And come, Egeus; you shall go with me. ",
" I have some private schooling for you both.— ",
" For you, fair Hermia, look you arm yourself ",
" To fit your fancies to your father’s will, ",
" Or else the law of Athens yields you up ",
" (Which by no means we may extenuate) ",
" To death, or to a vow of single life. ",
" Come, my Hippolyta. What cheer, my love? ",
" Demetrius and Egeus, go along; ",
" I must employ you in some business ",
" Against our nuptial, and confer with you ",
" Of something nearly that concerns yourselves. ",
" With duty and desire we follow you. ",
" How now, my love? Why is your cheek so pale? ",
" How chance the roses there do fade so fast? ",
" Belike for want of rain, which I could well ",
" Beteem them from the tempest of my eyes. ",
" Ay me! For aught that I could ever read, ",
" Could ever hear by tale or history, ",
" The course of true love never did run smooth. ",
" But either it was different in blood— ",
" O cross! Too high to be enthrall’d to low. ",
" Or else misgraffèd in respect of years— ",
" O spite! Too old to be engag’d to young. ",
" Or else it stood upon the choice of friends— ",
" O hell! to choose love by another’s eyes! ",
" Or, if there were a sympathy in choice, ",
" War, death, or sickness did lay siege to it, ",
" Making it momentany as a sound, ",
" Swift as a shadow, short as any dream, ",
" Brief as the lightning in the collied night ",
" That, in a spleen, unfolds both heaven and earth, ",
" And, ere a man hath power to say, ‘Behold!’ ",
" The jaws of darkness do devour it up: ",
" So quick bright things come to confusion. ",
" If then true lovers have ever cross’d, ",
" It stands as an edict in destiny. ",
" Then let us teach our trial patience, ",
" Because it is a customary cross, ",
" As due to love as thoughts and dreams and sighs, ",
" Wishes and tears, poor fancy’s followers. ",
" A good persuasion; therefore, hear me, Hermia. ",
" I have a widow aunt, a dowager ",
" Of great revenue, and she hath no child. ",
" From Athens is her house remote seven leagues, ",
" And she respects me as her only son. ",
" There, gentle Hermia, may I marry thee, ",
" And to that place the sharp Athenian law ",
" Cannot pursue us. If thou lovest me then, ",
" Steal forth thy father’s house tomorrow night; ",
" And in the wood, a league without the town ",
" (Where I did meet thee once with Helena ",
" To do observance to a morn of May), ",
" There will I stay for thee. ",
" My good Lysander! ",
" I swear to thee by Cupid’s strongest bow, ",
" By his best arrow with the golden head, ",
" By the simplicity of Venus’ doves, ",
" By that which knitteth souls and prospers loves, ",
" And by that fire which burn’d the Carthage queen ",
" When the false Trojan under sail was seen, ",
" By all the vows that ever men have broke ",
" (In number more than ever women spoke), ",
" In that same place thou hast appointed me, ",
" Tomorrow truly will I meet with thee. ",
" Keep promise, love. Look, here comes Helena. ",
" God speed fair Helena! Whither away? ",
" Call you me fair? That fair again unsay. ",
" Demetrius loves your fair. O happy fair! ",
" Your eyes are lode-stars and your tongue’s sweet air ",
" More tuneable than lark to shepherd’s ear, ",
" When wheat is green, when hawthorn buds appear. ",
" Sickness is catching. O were favour so, ",
" Yours would I catch, fair Hermia, ere I go. ",
" My ear should catch your voice, my eye your eye, ",
" My tongue should catch your tongue’s sweet melody. ",
" Were the world mine, Demetrius being bated, ",
" The rest I’d give to be to you translated. ",
" O, teach me how you look, and with what art ",
" You sway the motion of Demetrius’ heart! ",
" I frown upon him, yet he loves me still. ",
" O that your frowns would teach my smiles such skill! ",
" I give him curses, yet he gives me love. ",
" O that my prayers could such affection move! ",
" The more I hate, the more he follows me. ",
" The more I love, the more he hateth me. ",
" His folly, Helena, is no fault of mine. ",
" None but your beauty; would that fault were mine! ",
" Take comfort: he no more shall see my face; ",
" Lysander and myself will fly this place. ",
" Before the time I did Lysander see, ",
" Seem’d Athens as a paradise to me. ",
" O, then, what graces in my love do dwell, ",
" That he hath turn’d a heaven into hell! ",
" Helen, to you our minds we will unfold: ",
" Tomorrow night, when Phoebe doth behold ",
" Her silver visage in the watery glass, ",
" Decking with liquid pearl the bladed grass ",
" (A time that lovers’ flights doth still conceal), ",
" Through Athens’ gates have we devis’d to steal. ",
" And in the wood where often you and I ",
" Upon faint primrose beds were wont to lie, ",
" Emptying our bosoms of their counsel sweet, ",
" There my Lysander and myself shall meet, ",
" And thence from Athens turn away our eyes, ",
" To seek new friends and stranger companies. ",
" Farewell, sweet playfellow. Pray thou for us, ",
" And good luck grant thee thy Demetrius! ",
" Keep word, Lysander. We must starve our sight ",
" From lovers’ food, till morrow deep midnight. ",
" I will, my Hermia. ",
" Helena, adieu. ",
" As you on him, Demetrius dote on you! ",
" How happy some o’er other some can be! ",
" Through Athens I am thought as fair as she. ",
" But what of that? Demetrius thinks not so; ",
" He will not know what all but he do know. ",
" And as he errs, doting on Hermia’s eyes, ",
" So I, admiring of his qualities. ",
" Things base and vile, holding no quantity, ",
" Love can transpose to form and dignity. ",
" Love looks not with the eyes, but with the mind; ",
" And therefore is wing’d Cupid painted blind. ",
" Nor hath love’s mind of any judgment taste. ",
" Wings, and no eyes, figure unheedy haste. ",
" And therefore is love said to be a child, ",
" Because in choice he is so oft beguil’d. ",
" As waggish boys in game themselves forswear, ",
" So the boy Love is perjur’d everywhere. ",
" For, ere Demetrius look’d on Hermia’s eyne, ",
" He hail’d down oaths that he was only mine; ",
" And when this hail some heat from Hermia felt, ",
" So he dissolv’d, and showers of oaths did melt. ",
" I will go tell him of fair Hermia’s flight. ",
" Then to the wood will he tomorrow night ",
" Pursue her; and for this intelligence ",
" If I have thanks, it is a dear expense. ",
" But herein mean I to enrich my pain, ",
" To have his sight thither and back again. ",
" Is all our company here? ",
" You were best to call them generally, man by man, according to the ",
" scrip. ",
" Here is the scroll of every man’s name, which is thought fit through ",
" all Athens, to play in our interlude before the Duke and Duchess, on ",
" his wedding-day at night. ",
" First, good Peter Quince, say what the play treats on; then read the ",
" names of the actors; and so grow to a point. ",
" Marry, our play is _The most lamentable comedy and most cruel death of ",
" Pyramus and Thisbe_. ",
" A very good piece of work, I assure you, and a merry. Now, good Peter ",
" Quince, call forth your actors by the scroll. Masters, spread ",
" yourselves. ",
" Answer, as I call you. Nick Bottom, the weaver. ",
" Ready. Name what part I am for, and proceed. ",
" You, Nick Bottom, are set down for Pyramus. ",
" What is Pyramus—a lover, or a tyrant? ",
" A lover, that kills himself most gallantly for love. ",
" That will ask some tears in the true performing of it. If I do it, let ",
" the audience look to their eyes. I will move storms; I will condole in ",
" some measure. To the rest—yet my chief humour is for a tyrant. I could ",
" play Ercles rarely, or a part to tear a cat in, to make all split. ",
" The raging rocks ",
" And shivering shocks ",
" Shall break the locks ",
" Of prison gates, ",
" And Phibbus’ car ",
" Shall shine from far, ",
" And make and mar ",
" The foolish Fates. ",
" This was lofty. Now name the rest of the players. This is Ercles’ vein, ",
" a tyrant’s vein; a lover is more condoling. ",
" Francis Flute, the bellows-mender. ",
" Here, Peter Quince. ",
" Flute, you must take Thisbe on you. ",
" What is Thisbe? A wandering knight? ",
" It is the lady that Pyramus must love. ",
" Nay, faith, let not me play a woman. I have a beard coming. ",
" That’s all one. You shall play it in a mask, and you may speak as small ",
" as you will. ",
" And I may hide my face, let me play Thisbe too. I’ll speak in a ",
" monstrous little voice; ‘Thisne, Thisne!’—‘Ah, Pyramus, my lover dear! ",
" thy Thisbe dear! and lady dear!’ ",
" No, no, you must play Pyramus; and, Flute, you Thisbe. ",
" Well, proceed. ",
" Robin Starveling, the tailor. ",
" Here, Peter Quince. ",
" Robin Starveling, you must play Thisbe’s mother. ",
" Tom Snout, the tinker. ",
" Here, Peter Quince. ",
" You, Pyramus’ father; myself, Thisbe’s father; ",
" Snug, the joiner, you, the lion’s part. And, I hope here is a play ",
" fitted. ",
" Have you the lion’s part written? Pray you, if it be, give it me, for I ",
" am slow of study. ",
" You may do it extempore, for it is nothing but roaring. ",
" Let me play the lion too. I will roar that I will do any man’s heart ",
" good to hear me. I will roar that I will make the Duke say ‘Let him ",
" roar again, let him roar again.’ ",
" If you should do it too terribly, you would fright the Duchess and the ",
" ladies, that they would shriek; and that were enough to hang us all. ",
" That would hang us every mother’s son. ",
" I grant you, friends, if you should fright the ladies out of their ",
" wits, they would have no more discretion but to hang us. But I will ",
" aggravate my voice so, that I will roar you as gently as any sucking ",
" dove; I will roar you an ’twere any nightingale. ",
" You can play no part but Pyramus, for Pyramus is a sweet-faced man; a ",
" proper man as one shall see in a summer’s day; a most lovely ",
" gentleman-like man. Therefore you must needs play Pyramus. ",
" Well, I will undertake it. What beard were I best to play it in? ",
" Why, what you will. ",
" I will discharge it in either your straw-colour beard, your ",
" orange-tawny beard, your purple-in-grain beard, or your ",
" French-crown-colour beard, your perfect yellow. ",
" Some of your French crowns have no hair at all, and then you will play ",
" bare-faced. But, masters, here are your parts, and I am to entreat you, ",
" request you, and desire you, to con them by tomorrow night; and meet me ",
" in the palace wood, a mile without the town, by moonlight; there will ",
" we rehearse, for if we meet in the city, we shall be dogg’d with ",
" company, and our devices known. In the meantime I will draw a bill of ",
" properties, such as our play wants. I pray you fail me not. ",
" We will meet, and there we may rehearse most obscenely and ",
" courageously. Take pains, be perfect; adieu. ",
" At the Duke’s oak we meet. ",
" Enough. Hold, or cut bow-strings. ",
  ]

//   const data = [
//     " Now, fair Hippolyta, our nuptial hourDraws on apace; four happy days bring inAnother moon; but oh, methinks, how slowThis old moon wanes! She lingers my desires,Like to a step-dame or a dowager,Long withering out a young man’s revenue. ",
// " Four days will quickly steep themselves in night;Four nights will quickly dream away the time;And then the moon, like to a silver bowNew bent in heaven, shall behold the nightOf our solemnities. ",
// " Go, Philostrate,Stir up the Athenian youth to merriments;Awake the pert and nimble spirit of mirth;Turn melancholy forth to funerals;The pale companion is not for our pomp.Hippolyta, I woo’d thee with my sword,And won thy love doing thee injuries;But I will wed thee in another key,With pomp, with triumph, and with revelling. ",
// " Happy be Theseus, our renownèd Duke! ",
// " Thanks, good Egeus. What’s the news with thee? ",
// " Full of vexation come I, with complaintAgainst my child, my daughter Hermia.Stand forth, Demetrius. My noble lord,This man hath my consent to marry her.Stand forth, Lysander. And, my gracious Duke,This man hath bewitch’d the bosom of my child.Thou, thou, Lysander, thou hast given her rhymes,And interchang’d love-tokens with my child.Thou hast by moonlight at her window sung,With feigning voice, verses of feigning love;And stol’n the impression of her fantasyWith bracelets of thy hair, rings, gauds, conceits,Knacks, trifles, nosegays, sweetmeats (messengersOf strong prevailment in unharden’d youth)With cunning hast thou filch’d my daughter’s heart,Turn’d her obedience (which is due to me)To stubborn harshness. And, my gracious Duke,Be it so she will not here before your graceConsent to marry with Demetrius,I beg the ancient privilege of Athens:As she is mine I may dispose of her;Which shall be either to this gentlemanOr to her death, according to our lawImmediately provided in that case. ",
// " What say you, Hermia? Be advis’d, fair maid.To you your father should be as a god;One that compos’d your beauties, yea, and oneTo whom you are but as a form in waxBy him imprinted, and within his powerTo leave the figure, or disfigure it.Demetrius is a worthy gentleman. ",
// " So is Lysander. ",
// " In himself he is.But in this kind, wanting your father’s voice,The other must be held the worthier. ",
// " I would my father look’d but with my eyes. ",
// " Rather your eyes must with his judgment look. ",
// " I do entreat your Grace to pardon me.I know not by what power I am made bold,Nor how it may concern my modestyIn such a presence here to plead my thoughts:But I beseech your Grace that I may knowThe worst that may befall me in this case,If I refuse to wed Demetrius. ",
// " Either to die the death, or to abjureFor ever the society of men.Therefore, fair Hermia, question your desires,Know of your youth, examine well your blood,Whether, if you yield not to your father’s choice,You can endure the livery of a nun,For aye to be in shady cloister mew’d,To live a barren sister all your life,Chanting faint hymns to the cold fruitless moon.Thrice-blessèd they that master so their bloodTo undergo such maiden pilgrimage,But earthlier happy is the rose distill’dThan that which, withering on the virgin thorn,Grows, lives, and dies, in single blessedness. ",
// " So will I grow, so live, so die, my lord,Ere I will yield my virgin patent upUnto his lordship, whose unwishèd yokeMy soul consents not to give sovereignty. ",
// " Take time to pause; and by the next new moonThe sealing-day betwixt my love and meFor everlasting bond of fellowship,Upon that day either prepare to dieFor disobedience to your father’s will,Or else to wed Demetrius, as he would,Or on Diana’s altar to protestFor aye austerity and single life. ",
// " Relent, sweet Hermia; and, Lysander, yieldThy crazèd title to my certain right. ",
// " You have her father’s love, Demetrius.Let me have Hermia’s. Do you marry him. ",
// " Scornful Lysander, true, he hath my love;And what is mine my love shall render him;And she is mine, and all my right of herI do estate unto Demetrius. ",
// " I am, my lord, as well deriv’d as he,As well possess’d; my love is more than his;My fortunes every way as fairly rank’d,If not with vantage, as Demetrius’;And, which is more than all these boasts can be,I am belov’d of beauteous Hermia.Why should not I then prosecute my right?Demetrius, I’ll avouch it to his head,Made love to Nedar’s daughter, Helena,And won her soul; and she, sweet lady, dotes,Devoutly dotes, dotes in idolatry,Upon this spotted and inconstant man. ",
// " I must confess that I have heard so much,And with Demetrius thought to have spoke thereof;But, being over-full of self-affairs,My mind did lose it.—But, Demetrius, come,And come, Egeus; you shall go with me.I have some private schooling for you both.—For you, fair Hermia, look you arm yourselfTo fit your fancies to your father’s will,Or else the law of Athens yields you up(Which by no means we may extenuate)To death, or to a vow of single life.Come, my Hippolyta. What cheer, my love?Demetrius and Egeus, go along;I must employ you in some businessAgainst our nuptial, and confer with youOf something nearly that concerns yourselves. ",
// " With duty and desire we follow you. ",
// " How now, my love? Why is your cheek so pale?How chance the roses there do fade so fast? ",
// " Belike for want of rain, which I could wellBeteem them from the tempest of my eyes. ",
// " Ay me! For aught that I could ever read,Could ever hear by tale or history,The course of true love never did run smooth.But either it was different in blood— ",
// " O cross! Too high to be enthrall’d to low. ",
// " Or else misgraffèd in respect of years— ",
// " O spite! Too old to be engag’d to young. ",
// " Or else it stood upon the choice of friends— ",
// " O hell! to choose love by another’s eyes! ",
// " Or, if there were a sympathy in choice,War, death, or sickness did lay siege to it,Making it momentany as a sound,Swift as a shadow, short as any dream,Brief as the lightning in the collied nightThat, in a spleen, unfolds both heaven and earth,And, ere a man hath power to say, ‘Behold!’The jaws of darkness do devour it up:So quick bright things come to confusion. ",
// " If then true lovers have ever cross’d,It stands as an edict in destiny.Then let us teach our trial patience,Because it is a customary cross,As due to love as thoughts and dreams and sighs,Wishes and tears, poor fancy’s followers. ",
// " A good persuasion; therefore, hear me, Hermia.I have a widow aunt, a dowagerOf great revenue, and she hath no child.From Athens is her house remote seven leagues,And she respects me as her only son.There, gentle Hermia, may I marry thee,And to that place the sharp Athenian lawCannot pursue us. If thou lovest me then,Steal forth thy father’s house tomorrow night;And in the wood, a league without the town(Where I did meet thee once with HelenaTo do observance to a morn of May),There will I stay for thee. ",
// " My good Lysander!I swear to thee by Cupid’s strongest bow,By his best arrow with the golden head,By the simplicity of Venus’ doves,By that which knitteth souls and prospers loves,And by that fire which burn’d the Carthage queenWhen the false Trojan under sail was seen,By all the vows that ever men have broke(In number more than ever women spoke),In that same place thou hast appointed me,Tomorrow truly will I meet with thee. ",
// " Keep promise, love. Look, here comes Helena. ",
// " God speed fair Helena! Whither away? ",
// " Call you me fair? That fair again unsay.Demetrius loves your fair. O happy fair!Your eyes are lode-stars and your tongue’s sweet airMore tuneable than lark to shepherd’s ear,When wheat is green, when hawthorn buds appear.Sickness is catching. O were favour so,Yours would I catch, fair Hermia, ere I go.My ear should catch your voice, my eye your eye,My tongue should catch your tongue’s sweet melody.Were the world mine, Demetrius being bated,The rest I’d give to be to you translated.O, teach me how you look, and with what artYou sway the motion of Demetrius’ heart! ",
// " I frown upon him, yet he loves me still. ",
// " O that your frowns would teach my smiles such skill! ",
// " I give him curses, yet he gives me love. ",
// " O that my prayers could such affection move! ",
// " The more I hate, the more he follows me. ",
// " The more I love, the more he hateth me. ",
// " His folly, Helena, is no fault of mine. ",
// " None but your beauty; would that fault were mine! ",
// " Take comfort: he no more shall see my face;Lysander and myself will fly this place.Before the time I did Lysander see,Seem’d Athens as a paradise to me.O, then, what graces in my love do dwell,That he hath turn’d a heaven into hell! ",
// " Helen, to you our minds we will unfold:Tomorrow night, when Phoebe doth beholdHer silver visage in the watery glass,Decking with liquid pearl the bladed grass(A time that lovers’ flights doth still conceal),Through Athens’ gates have we devis’d to steal. ",
// " And in the wood where often you and IUpon faint primrose beds were wont to lie,Emptying our bosoms of their counsel sweet,There my Lysander and myself shall meet,And thence from Athens turn away our eyes,To seek new friends and stranger companies.Farewell, sweet playfellow. Pray thou for us,And good luck grant thee thy Demetrius!Keep word, Lysander. We must starve our sightFrom lovers’ food, till morrow deep midnight. ",
// " I will, my Hermia.Helena, adieu.As you on him, Demetrius dote on you! ",
// " How happy some o’er other some can be!Through Athens I am thought as fair as she.But what of that? Demetrius thinks not so;He will not know what all but he do know.And as he errs, doting on Hermia’s eyes,So I, admiring of his qualities.Things base and vile, holding no quantity,Love can transpose to form and dignity.Love looks not with the eyes, but with the mind;And therefore is wing’d Cupid painted blind.Nor hath love’s mind of any judgment taste.Wings, and no eyes, figure unheedy haste.And therefore is love said to be a child,Because in choice he is so oft beguil’d.As waggish boys in game themselves forswear,So the boy Love is perjur’d everywhere.For, ere Demetrius look’d on Hermia’s eyne,He hail’d down oaths that he was only mine;And when this hail some heat from Hermia felt,So he dissolv’d, and showers of oaths did melt.I will go tell him of fair Hermia’s flight.Then to the wood will he tomorrow nightPursue her; and for this intelligenceIf I have thanks, it is a dear expense.But herein mean I to enrich my pain,To have his sight thither and back again. ",
// " Is all our company here? ",
// " You were best to call them generally, man by man, according to thescrip. ",
// " Here is the scroll of every man’s name, which is thought fit throughall Athens, to play in our interlude before the Duke and Duchess, onhis wedding-day at night. ",
// " First, good Peter Quince, say what the play treats on; then read thenames of the actors; and so grow to a point. ",
// " Marry, our play is _The most lamentable comedy and most cruel death ofPyramus and Thisbe_. ",
// " A very good piece of work, I assure you, and a merry. Now, good PeterQuince, call forth your actors by the scroll. Masters, spreadyourselves. ",
// " Answer, as I call you. Nick Bottom, the weaver. ",
// " Ready. Name what part I am for, and proceed. ",
// " You, Nick Bottom, are set down for Pyramus. ",
// " What is Pyramus—a lover, or a tyrant? ",
// " A lover, that kills himself most gallantly for love. ",
// " That will ask some tears in the true performing of it. If I do it, letthe audience look to their eyes. I will move storms; I will condole insome measure. To the rest—yet my chief humour is for a tyrant. I couldplay Ercles rarely, or a part to tear a cat in, to make all split.The raging rocksAnd shivering shocksShall break the locksOf prison gates,And Phibbus’ carShall shine from far,And make and marThe foolish Fates.This was lofty. Now name the rest of the players. This is Ercles’ vein,a tyrant’s vein; a lover is more condoling. ",
// " Francis Flute, the bellows-mender. ",
// " Here, Peter Quince. ",
// " Flute, you must take Thisbe on you. ",
// " What is Thisbe? A wandering knight? ",
// " It is the lady that Pyramus must love. ",
// " Nay, faith, let not me play a woman. I have a beard coming. ",
// " That’s all one. You shall play it in a mask, and you may speak as smallas you will. ",
// " And I may hide my face, let me play Thisbe too. I’ll speak in amonstrous little voice; ‘Thisne, Thisne!’—‘Ah, Pyramus, my lover dear!thy Thisbe dear! and lady dear!’ ",
// " No, no, you must play Pyramus; and, Flute, you Thisbe. ",
// " Well, proceed. ",
// " Robin Starveling, the tailor. ",
// " Here, Peter Quince. ",
// " Robin Starveling, you must play Thisbe’s mother.Tom Snout, the tinker. ",
// " Here, Peter Quince. ",
// " You, Pyramus’ father; myself, Thisbe’s father;Snug, the joiner, you, the lion’s part. And, I hope here is a playfitted. ",
// " Have you the lion’s part written? Pray you, if it be, give it me, for Iam slow of study. ",
// " You may do it extempore, for it is nothing but roaring. ",
// " Let me play the lion too. I will roar that I will do any man’s heartgood to hear me. I will roar that I will make the Duke say ‘Let himroar again, let him roar again.’ ",
// " If you should do it too terribly, you would fright the Duchess and theladies, that they would shriek; and that were enough to hang us all. ",
// " That would hang us every mother’s son. ",
// " I grant you, friends, if you should fright the ladies out of theirwits, they would have no more discretion but to hang us. But I willaggravate my voice so, that I will roar you as gently as any suckingdove; I will roar you an ’twere any nightingale. ",
// " You can play no part but Pyramus, for Pyramus is a sweet-faced man; aproper man as one shall see in a summer’s day; a most lovelygentleman-like man. Therefore you must needs play Pyramus. ",
// " Well, I will undertake it. What beard were I best to play it in? ",
// " Why, what you will. ",
// " I will discharge it in either your straw-colour beard, yourorange-tawny beard, your purple-in-grain beard, or yourFrench-crown-colour beard, your perfect yellow. ",
// " Some of your French crowns have no hair at all, and then you will playbare-faced. But, masters, here are your parts, and I am to entreat you,request you, and desire you, to con them by tomorrow night; and meet mein the palace wood, a mile without the town, by moonlight; there willwe rehearse, for if we meet in the city, we shall be dogg’d withcompany, and our devices known. In the meantime I will draw a bill ofproperties, such as our play wants. I pray you fail me not. ",
// " We will meet, and there we may rehearse most obscenely andcourageously. Take pains, be perfect; adieu. ",
// " At the Duke’s oak we meet. ",
//   ];

  return (
    <div>
      <RadialTextChart 
      data={stuff} 
      width={1000} 
      height={1000} 
      centerText="I"
      />
      
    </div>
  );
}
